# Generated by Django 5.1.6 on 2025-03-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='updated_at',
        ),
    ]
